<?php

namespace App\Models;

use App\Tenancy\BelongsToTenant;
use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Str;

class Appointment extends Model
{
    use HasFactory;
    use Searchable;
    use BelongsToTenant;

    protected $fillable = [
        'start_time',
        'end_time',
        'uuid',
        'token',
        'cancelled_at',
        'user_id',
        'patient_id',
        'schedule_id',
        'service_id',
    ];

    protected $searchableFields = ['*'];

    protected $casts = [
        'cancelled_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($appointment) {
            $appointment->uuid = (string) Str::uuid();
            $appointment->token = (string) Str::random(25);
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }

    public function schedule()
    {
        return $this->belongsTo(Schedule::class);
    }

    public function service()
    {
        return $this->belongsTo(Service::class);
    }
}
